### ISSUE TITLE
Add CI workflows to enhance the dev experience

### ISSUE THREAD

**Issue by umbynos** [arduino/avrdude-packing#17]
Add some checks workflows to this repo to enhance the developer experience and to catch common problems:
https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-markdown-task.md
https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-workflows-task.md

**Comment by MatteoPologruto** [comment]
- Check-markdown-task was added in PR #18 
- Check-workflows-task was added in PR #19
