### ISSUE TITLE
avrdude 100% cpu usage

### ISSUE THREAD

**Issue by All3xJ** [arduino/avrdude-packing#21]
This bug is a duplicate of arduino/Arduino#7498 , but it's closed.
I just noticed that my pc was lagging, so I checked with htop, and I have:
![image](https://user-images.githubusercontent.com/20903913/145725277-ac02b603-d252-45a2-b518-b0609d754bd7.png)
Arduino IDE is closed, and the microcontroller is not attached to PC.
Arduino: 1.8.16
ArchLinux

**Comment by umbynos** [comment]
@All3xJ could you please test with https://github.com/arduino/avrdude-packing/releases/tag/7.1-arduino.1?

**Comment by umbynos** [comment]
Closing for lack of feedback. Feel free to reopen if needed
