### ISSUE TITLE
Writing Lockbit AtMega4808 failed

### ISSUE THREAD

**Issue by rsVenotec** [arduino/avrdude-packing#34]
Hello everyone, I'm not sure if I'm doing something wrong but I can write fuses and flash of the Atmegas with AvrDude but I can't lock the controller afterwards.
Im using a PicKit5 with avrdude version 8.0-arduino.1 
I also tried to use avrdude version 8.0 from real avrdude repository but this could not even communicate with the PicKit. 

Here is the command including the feedback from AVRDUDESS:
```
Writing lock bits...
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
: avrdude.exe -c pickit5_updi -p m4808 -P usb -b 200000 -F -U lock:w:0xC6:m 
Reading 1 byte for lock from input file 0xC6
Writing 1 byte (0xC6) to lock, 1 byte written
Warning: lock verification mismatch
  device 0xc5 != input 0xc6 at addr 0x0000 (error)
Error: lock verification mismatch

Avrdude done.  Thank you.
```

I also tried to implement the lockbits in the hex file, but this did not help anyway, but uploading the hex file with MPLABX IPE blocks the controller, fine. Am I doing something wrong or is this a bug?

That the verification fails would make sense to me, but the writing already fails because a readout results in 0xC5 again.
Is this a problem with the new megaAVR 0-series?

**Comment by per1234** [comment]
Hi @rsVenotec. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/c/using-arduino/avrdude-stk500-bootloader-issues/81
