### ISSUE TITLE
Are the libraries in the Linux releases statically linked?

### ISSUE THREAD

**Issue by kristofmulier** [arduino/avrdude-packing#4]
I assume this new repository is the official Arduino repo for `AVRDUDE` releases.

I have a few questions about the Linux releases:

 - Which libraries are statically and which are dynamically linked?
 - Did you build the releases on an old Linux system, such that it can run on both modern and old systems?

I would like to draw your attention on this discussion on the official `AVRDUDE` GitHub page:

https://github.com/avrdudes/avrdude/issues/987

Here the `AVRDUDE` founders and maintainers are discussing the Linux builds. Please participate in the discussion.

**Comment by umbynos** [comment]
Answered in https://github.com/avrdudes/avrdude/issues/987#issuecomment-1150986042
